# Generated by Django 5.2.8 on 2026-01-06 02:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_umkm_verification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UMKMGallery',
            fields=[
                ('gallery_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('umkm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='account.umkm')),
            ],
        ),
        migrations.CreateModel(
            name='UMKMProduct',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=200)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image_url', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('umkm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='account.umkm')),
            ],
        ),
        migrations.CreateModel(
            name='UMKMReview',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('umkm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='account.umkm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UMKMService',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_service', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('harga_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('harga_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimasi_waktu', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('umkm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='account.umkm')),
            ],
        ),
    ]
