# Generated by Django 5.2.8 on 2026-01-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_umkmgallery_umkmproduct_umkmreview_umkmservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='umkmgallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='umkmgallery',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
