# Generated by Django 5.2.8 on 2026-01-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_umkmgallery_image_alter_umkmgallery_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='umkmreview',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='umkmreview',
            name='reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
