# Generated by Django 5.2.8 on 2026-05-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_umkm_analytics'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='umkmvisit',
            new_name='account_umk_umkm_id_28e8c7_idx',
            old_name='account_umkmv_umkm_id_visit_d5b81f_idx',
        ),
    ]
